blank_issues_enabled: false
contact_links:
    - name: Support
      url: https://github.com/neohugo/neohugo/discussions
      about: Visit https://github.com/neohugo/neohugo/discussions for support.
